import unittest
from pathlib import Path


class ReaderUiTests(unittest.TestCase):
    def test_preview_template_has_toc_and_controls(self) -> None:
        root = Path(__file__).resolve().parent.parent
        tpl = (root / "templates" / "preview.html").read_text(encoding="utf-8")

        self.assertIn('x-data="binderyReader()', tpl)
        self.assertIn("目录", tpl)
        self.assertIn('x-model="fontFamily"', tpl)
        self.assertIn("fontSize", tpl)
        self.assertIn("上一页", tpl)
        self.assertIn("下一页", tpl)
        self.assertIn("pageCount", tpl)
        self.assertIn("pagePrev", tpl)
        self.assertIn("pageNext", tpl)
        self.assertIn("bindery-reader-scroller", tpl)
        self.assertIn('x-ref="frameA"', tpl)
        self.assertIn('x-ref="frameB"', tpl)
        self.assertIn(":style=\"activeFrameKey === 'a' ? 'opacity:1;z-index:10;pointer-events:auto;' : 'opacity:0;z-index:0;pointer-events:none;'\"", tpl)
        self.assertIn(":style=\"activeFrameKey === 'b' ? 'opacity:1;z-index:10;pointer-events:auto;' : 'opacity:0;z-index:0;pointer-events:none;'\"", tpl)
        self.assertIn("styleMode", tpl)
        self.assertIn("settingsOpen", tpl)
        self.assertIn("searchOpen", tpl)
        self.assertIn("全文检索", tpl)
        self.assertIn("runSearch()", tpl)
        self.assertIn("searchBusy", tpl)
        self.assertIn("searchResults", tpl)
        self.assertIn("searchHasMore", tpl)
        self.assertIn("searchOffset", tpl)
        self.assertIn("loadMoreSearch()", tpl)
        self.assertIn("openSearchResult", tpl)
        self.assertIn("highlightSearchText", tpl)
        self.assertIn("_escapeHtml", tpl)
        self.assertIn("_searchMarkClass", tpl)
        self.assertIn("searchIndexedSections", tpl)
        self.assertIn("readerBg", tpl)
        self.assertIn("brightnessMode", tpl)
        self.assertIn("亮色", tpl)
        self.assertIn("暗色", tpl)
        self.assertIn("lineHeight", tpl)
        self.assertIn("textAlignMode", tpl)
        self.assertIn("pagePaddingX", tpl)
        self.assertIn("pagePaddingY", tpl)
        self.assertIn("设置", tpl)
        self.assertIn("binderyKeyListener", tpl)
        self.assertIn("--bindery-reader-bg", tpl)
        self.assertIn("--bindery-reader-text", tpl)
        self.assertIn("书籍", tpl)
        self.assertIn("自定义", tpl)
        self.assertIn("tocOpen ? 'translate-x-1' : '-translate-x-full'", tpl)
        self.assertIn('src="{{ book.cover_url }}"', tpl)
        self.assertIn("timeNow", tpl)
        self.assertIn("data-current-toc", tpl)
        self.assertIn("resumeRequested", tpl)
        self.assertIn("scrollIntoView", tpl)
        self.assertIn("navReason", tpl)
        self.assertNotIn("scroll-snap-type:x mandatory", tpl)
        self.assertIn("_captureViewportAnchor", tpl)
        self.assertIn("_restoreViewportAnchor", tpl)
        self.assertIn("_prefetchSectionHtml", tpl)
        self.assertIn("requestIdleCallback", tpl)
        self.assertIn("chapterSwitching", tpl)
        self.assertIn("gotoSection", tpl)
        self.assertIn("decMarginX", tpl)
        self.assertIn("incMarginX", tpl)
        self.assertIn("decMarginY", tpl)
        self.assertIn("incMarginY", tpl)
        self.assertIn("两端对齐", tpl)
        self.assertIn("text-justify", tpl)
        self.assertIn("frame.src = section.content_url", tpl)
        self.assertIn("new URL(`/book/${this.bookId}/search`", tpl)
        self.assertIn('url.searchParams.set("offset"', tpl)
        self.assertIn('url.searchParams.set("limit"', tpl)
        self.assertIn("payload.indexed_sections", tpl)
        self.assertIn("_schedulePaginationRefresh", tpl)
        self.assertNotIn("Math.floor(maxLeft / width) + 1", tpl)
        self.assertIn("Math.min(metrics.maxLeft", tpl)
        self.assertIn("--bindery-page-step", tpl)
        self.assertIn("--bindery-page-tail-pad", tpl)
        self.assertNotIn("--bindery-reader-brightness", tpl)
        self.assertNotIn("bindery-bright-dim", tpl)
        self.assertNotIn("bindery-bright-bright", tpl)
        self.assertIn("padding-right:var(--bindery-page-padding-x,0px)!important;margin-top:0!important;margin-bottom:0!important;margin-left:0!important;margin-right:var(--bindery-page-tail-pad,0px)!important", tpl)
        self.assertIn("#bindery-reader-pages{display:block!important;position:relative!important;float:none!important;clear:both!important;width:100%!important;min-width:100%!important", tpl)
        self.assertIn("Math.floor(maxLeft / step) + 1", tpl)
        self.assertIn("Math.floor((scroller.scrollLeft + 1) / metrics.step) + 1", tpl)
        self.assertIn("this.scrollByPages(-1)", tpl)
        self.assertIn("this.scrollByPages(1)", tpl)
        self.assertIn("const effectivePaddingX = Math.max(0, paddingX);", tpl)
        self.assertIn("const columnWidth = Math.max(1, width - effectivePaddingX * 2);", tpl)
        self.assertIn("const columnGap = Math.max(0, effectivePaddingX * 2);", tpl)
        self.assertIn("const pageStep = width;", tpl)
        self.assertIn("const lastPageTarget = 99998;", tpl)
        self.assertIn("desiredPage: lastPageTarget", tpl)
        self.assertIn("Number.parseInt(String(value || \"\"), 10)", tpl)
        self.assertIn("Number.parseInt(String(targetIndex), 10)", tpl)
        self.assertNotIn("Number.parseInt(String(value || \"\"), 9)", tpl)
        self.assertNotIn("Number.parseInt(String(targetIndex), 9)", tpl)
        self.assertIn("targetNode.nodeType !== 3", tpl)
        self.assertIn("Math.max(0, Number(caret.offset) || 0)", tpl)
        self.assertNotIn("Number(pos.offset) || -1", tpl)
        self.assertNotIn("Number(range.startOffset) || -1", tpl)
        self.assertIn("_recomputeTailPad", tpl)
        self.assertIn('scroller.addEventListener("scrollend"', tpl)
        self.assertNotIn("_snapTimer", tpl)
        self.assertNotIn("_scrollRaf", tpl)
        self.assertNotIn("frame.srcdoc", tpl)
        self.assertNotIn('removeAttribute("srcdoc")', tpl)
        self.assertNotIn("opacity-101", tpl)
        self.assertNotIn("md:opacity-0", tpl)
        self.assertNotIn("md:group-hover:opacity-100", tpl)

    def test_base_supports_fullscreen_layout(self) -> None:
        root = Path(__file__).resolve().parent.parent
        base = (root / "templates" / "base.html").read_text(encoding="utf-8")
        self.assertIn("hide_nav", base)
        self.assertIn("main_class", base)


if __name__ == "__main__":
    unittest.main()
