import unittest
from pathlib import Path


class ReaderUiTests(unittest.TestCase):
    def test_preview_template_has_toc_and_controls(self) -> None:
        root = Path(__file__).resolve().parent.parent
        tpl = (root / "templates" / "preview.html").read_text(encoding="utf-8")

        self.assertIn('x-data="binderyReader()', tpl)
        self.assertIn("目录", tpl)
        self.assertIn('x-model="fontFamily"', tpl)
        self.assertIn("fontSize", tpl)
        self.assertIn("上一页", tpl)
        self.assertIn("下一页", tpl)
        self.assertIn("pageCount", tpl)
        self.assertIn("pagePrev", tpl)
        self.assertIn("pageNext", tpl)
        self.assertIn("bindery-reader-scroller", tpl)
        self.assertIn('x-ref="frameA"', tpl)
        self.assertIn('x-ref="frameB"', tpl)
        self.assertIn("styleMode", tpl)
        self.assertIn("settingsOpen", tpl)
        self.assertIn("searchOpen", tpl)
        self.assertIn("全文检索", tpl)
        self.assertIn("runSearch()", tpl)
        self.assertIn("searchBusy", tpl)
        self.assertIn("searchResults", tpl)
        self.assertIn("openSearchResult", tpl)
        self.assertIn("searchIndexedSections", tpl)
        self.assertIn("readerBg", tpl)
        self.assertIn("brightnessMode", tpl)
        self.assertIn("明亮", tpl)
        self.assertIn("柔和", tpl)
        self.assertIn("lineHeight", tpl)
        self.assertIn("textAlignMode", tpl)
        self.assertIn("pagePaddingX", tpl)
        self.assertIn("pagePaddingY", tpl)
        self.assertIn("设置", tpl)
        self.assertIn("binderyKeyListener", tpl)
        self.assertIn("bindery-theme-on", tpl)
        self.assertIn("书籍", tpl)
        self.assertIn("自定义", tpl)
        self.assertIn(":class=\"tocOpen ? 'translate-x-1' : '-translate-x-full'\"", tpl)
        self.assertIn('src="{{ book.cover_url }}"', tpl)
        self.assertIn("timeNow", tpl)
        self.assertIn("data-current-toc", tpl)
        self.assertIn("resumeRequested", tpl)
        self.assertIn("scrollIntoView", tpl)
        self.assertIn("navReason", tpl)
        self.assertNotIn("scroll-snap-type:x mandatory", tpl)
        self.assertIn("_captureViewportAnchor", tpl)
        self.assertIn("_restoreViewportAnchor", tpl)
        self.assertIn("_prefetchSectionHtml", tpl)
        self.assertIn("requestIdleCallback", tpl)
        self.assertIn("chapterSwitching", tpl)
        self.assertIn("gotoSection", tpl)
        self.assertIn("decMarginX", tpl)
        self.assertIn("incMarginX", tpl)
        self.assertIn("decMarginY", tpl)
        self.assertIn("incMarginY", tpl)
        self.assertIn("两端对齐", tpl)
        self.assertIn("text-justify", tpl)
        self.assertIn("frame.src = section.content_url", tpl)
        self.assertIn("new URL(`/book/${this.bookId}/search`", tpl)
        self.assertIn("payload.indexed_sections", tpl)
        self.assertIn("_schedulePaginationRefresh", tpl)
        self.assertNotIn("Math.floor(maxLeft / width) + 1", tpl)
        self.assertIn("Math.min(metrics.maxLeft", tpl)
        self.assertIn("--bindery-page-step", tpl)
        self.assertIn("--bindery-page-tail-pad", tpl)
        self.assertIn("--bindery-reader-brightness", tpl)
        self.assertIn("bindery-bright-dim", tpl)
        self.assertIn("bindery-bright-bright", tpl)
        self.assertIn("padding-right:calc(var(--bindery-page-padding-x,0px) + var(--bindery-page-tail-pad,0px))", tpl)
        self.assertIn("Math.floor(maxLeft / step) + 1", tpl)
        self.assertIn("Math.floor((scroller.scrollLeft + 1) / metrics.step) + 1", tpl)
        self.assertIn("this.scrollByPages(-1)", tpl)
        self.assertIn("this.scrollByPages(1)", tpl)
        self.assertIn("const columnWidth = Math.max(1, width);", tpl)
        self.assertIn("_recomputeTailPad", tpl)
        self.assertIn('scroller.addEventListener("scrollend"', tpl)
        self.assertNotIn("_snapTimer", tpl)
        self.assertNotIn("_scrollRaf", tpl)
        self.assertNotIn("frame.srcdoc", tpl)
        self.assertNotIn('removeAttribute("srcdoc")', tpl)
        self.assertNotIn("md:opacity-0", tpl)
        self.assertNotIn("md:group-hover:opacity-100", tpl)

    def test_base_supports_fullscreen_layout(self) -> None:
        root = Path(__file__).resolve().parent.parent
        base = (root / "templates" / "base.html").read_text(encoding="utf-8")
        self.assertIn("hide_nav", base)
        self.assertIn("main_class", base)


if __name__ == "__main__":
    unittest.main()
